### ISSUE TITLE
Return slant value as part of Apperance

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontquant#1]
Along with weight and width, slant is a primary property of any type style, and just like weight and width OS/2 table metadata, the slant value is completely unreliable.

I believe calculating the slant of `H` or similar vertical stem characters can be straightforward, if there's not already something in the fonttools toolbox :)

**Comment by behdad** [comment]
StatisticsPen has some code for that.

**Comment by yanone** [comment]
Done
