### ISSUE TITLE
Assess arbitrary and default (not zero origin) variable font design space locations

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontquant#2]
I think variable fonts are currently processed only at the ['zero origin'](https://learn.microsoft.com/en-us/typography/opentype/spec/otvaroverview) location (e.g. the `Thin` 100 style within a VF with a `wght` axis from 100 to 900; A.K.A. the glyf table's design), and it will be important to be able to assess arbitrary design space locations.

1. add a new arg to allow users to pass in any design space location as an input, validate it with the given font, and
2. use the github.com/googlefonts/axisregistry data to obtain the default location of an axis and use this instead of the zero origin when no design space location is provided

**Comment by yanone** [comment]
Done
