### ISSUE TITLE
All caps, small caps, mixed case

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontquant#5]
New check that returns the 'hard' casing baked into the font

**Comment by yanone** [comment]
Implemented as per https://github.com/googlefonts/fontquant/commit/f5fabaf4a4dc2236a3eb579b7d0655b34a61867b. Metric is called [Lowercase Shapes](https://github.com/googlefonts/fontquant/blob/main/Lib/fontquant/README.md#lowercase-shapes-casinglowercase_shapes)
