### ISSUE TITLE
New values: Parametric Axes (auto-parama-round-up)

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontquant#8]
https://github.com/FontBureau/Parama-roundup is a project led by @dberlow to 'round up' parametric values, where the work to identify specific glyphs (and specific contours and points) to measure, is handled manually by the user looking at point/contour attribute/metadata panels in their font editor and inputing these ID indices into a Google Sheet; the python script then does the measurement and writes the distance values back into the sheet. 

This issue then tracks the ability of fontquant to check and return these values automatically. 

Knowing these values for arbitrary (even static) fonts is required to do ["faux foundry"](https://web.archive.org/web/20210411073210/https://www.fauxfoundry.com/why) ([atypi video](https://www.youtube.com/watch?v=pYNz-fST-Sg)) like style-matching, or ["calibrated typography"](https://www.youtube.com/watch?v=1zjbWtv_UXs).

The most complete sets of parametric axes demonstrations in real fonts today are in the 'avar2' R&D versions (under active development) of [Amstelvar](https://github.com/googlefonts/amstelvar-avar2) and [Roboto Flex](https://github.com/googlefonts/roboto-flex-avar2). The Parama-RoundUp repo links to an older [Amstelvar Roundup Google Sheet](https://docs.google.com/spreadsheets/d/1L1Cy2Y1JFOl32nuevTkzcxjNsSTlLGn_oiRLkMnyonY) which may correspond to the files in https://github.com/googlefonts/amstelvar/tree/main/fonts but that would need to be tested.

**Comment by simoncozens** [comment]
Done!
